Added screen to update navbar title
awslabs/performance-dashboard-on-aws pull request #207
Opened 2021-01-01 00:55 UTC by jenboydclark

## Description

Added new screen to update the navbar title. Updated settings hooks to support the new field. Updated public and admin layouts to use the navbar title. 

## Testing

https://dvinr4n9hngnv.cloudfront.net/admin/settings/publishedsite

---

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-01-04 05:38 UTC, ferdingler requested changes, later dismissed

2021-01-04 05:38 UTC, ferdingler commented on frontend/src/layouts/Public.tsx
> +  const { settings } = useSettings();
Since this is a public screen, this should use the `usePublicSettings` hook instead. Otherwise settings won't load for non-authenticated users.

2021-01-04 05:38 UTC, ferdingler commented on frontend/src/models/index.tsx
> +  navbarTitle?: string;
Can you also add a default value for this property in the `context/SettingsProvider.ts` please? — Set the default value to 'Performance Dashboard' just like you did in the backend.

2021-01-05 23:08 UTC, miguelpdiaz8 approved these changes

2021-01-05 23:11 UTC, merged